export const blogs = {
  "blogs": {
    "hero":{
    "heading": "Latest Insights & Blogs",
    "descrip": "Stay updated with the latest trends and insights in fintech and payment solutions",
    },
        "posts": {
      "heading": "",
      "descrip": "Latest press releases and company announcements",
    "slides": [
      {
        "id": 1,
        "src": "https://simplifipay.com/images/blogs/001.png",
        "alt": "Components of launching your own branded cards",
        "subtitle": "Spending across virtually all markets and use cases is increasingly migrating to digital means with cards accounting for the lion's...",
        "title": "Launching your own card program – SimpliFied",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/components-of-launching-your-own-branded-cards-simplified",
        "date": "September 13, 2023",
        "slug": "components-of-launching-your-own-branded-cards-simplified",
        "path": "/blog/components-of-launching-your-own-branded-cards-simplified",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 2,
        "src": "https://simplifipay.com/images/blogs/002.jpg",
        "alt": "Global Compliance SimpliFied",
        "subtitle": "Compliance refers to the adherence to a set of regulations and industry standards designed to protect consumers and ensure the...",
        "title": "Global Compliance SimpliFied",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/what-is-global-compliance",
        "date": "February 03, 2023",
        "slug": "what-is-global-compliance",
        "path": "/blog/what-is-global-compliance",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 3,
        "src": "https://simplifipay.com/images/blogs/003.jpg",
        "alt": "What is a Virtual Card",
        "subtitle": "A Virtual Card is a payment card that exists solely in electronic form. It consists of a unique, randomly- generated...",
        "title": "What is a Virtual Card | Fintech explained by SimpliFi",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/what-is-a-virtual-card",
        "date": "December 09, 2022",
        "slug": "what-is-a-virtual-card",
        "path": "/blog/what-is-a-virtual-card",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 4,
        "src": "https://simplifipay.com/images/blogs/004.jpg",
        "alt": "What is KYC",
        "subtitle": "KYC is one of the most important terms in Fintech, and the financial ecosystem at large.What is KYC, you ask...",
        "title": "What is KYC? – Fintech Explained by SimpliFi",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/what-is-kyc",
        "date": "November 11, 2022",
        "slug": "what-is-kyc",
        "path": "/blog/what-is-kyc",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 5,
        "src": "https://simplifipay.com/images/blogs/005.png",
        "alt": "Open Loop Payment System",
        "subtitle": "Open-loop means any payment method can be used to make payments without having to be part of the system itself...",
        "title": "What is an Open Loop Payment System? Fintech Explained by SimpliFi",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/open-loop-payment-system",
        "date": "November 04, 2022",
        "slug": "open-loop-payment-system",
        "path": "/blog/open-loop-payment-system",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 6,
        "src": "https://simplifipay.com/images/blogs/006.jpg",
        "alt": "Designing Modern Card Offering",
        "subtitle": "In 2022, people and businesses continue to use payment cards every day – if not several times a day...",
        "title": "9 Things to Consider When Designing a Modern Card Offering",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/launching-card-offerings",
        "date": "October 14, 2022",
        "slug": "launching-card-offerings",
        "path": "/blog/launching-card-offerings",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 7,
        "src": "https://simplifipay.com/images/blogs/007.png",
        "alt": "Modern Card Issuing Vs Legacy Systems",
        "subtitle": "The magic of seamless, nearly invisible payments is spreading everywhere – on e-commerce sites...",
        "title": "Modern Card Issuing Vs. Legacy Systems: What is the difference?",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/modern-card-issuing-vs-legacy-systems",
        "date": "September 02, 2022",
        "slug": "modern-card-issuing-vs-legacy-systems",
        "path": "/blog/modern-card-issuing-vs-legacy-systems",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 8,
        "src": "https://simplifipay.com/images/blogs/008.jpg",
        "alt": "Payment Tokenization",
        "subtitle": "Tokenization has become a major buzzword these days and is often mentioned in the same breath as data security, blockchain...",
        "title": "What is Payment Tokenization? – Fintech Explained By SimpliFi",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/what-is-payment-tokenization-fintech-explained-by-simplifi",
        "date": "August 12, 2022",
        "slug": "what-is-payment-tokenization-fintech-explained-by-simplifi",
        "path": "/blog/what-is-payment-tokenization-fintech-explained-by-simplifi",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 9,
        "src": "https://simplifipay.com/images/blogs/009.jpg",
        "alt": "Card Scheme",
        "subtitle": "In any given payment card transaction there are multiple entities involved in the processing of those transactions...",
        "title": "Card Scheme: Fintech Explained by SimpliFi",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/what-is-a-card-scheme",
        "date": "July 08, 2022",
        "slug": "what-is-a-card-scheme",
        "path": "/blog/what-is-a-card-scheme",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 10,
        "src": "https://simplifipay.com/images/blogs/010.jpg",
        "alt": "Modern Card Issuing",
        "subtitle": "For decades, legacy payment infrastructure has enabled the payment of goods and services globally, reliably and securely...",
        "title": "How is Modern Card Issuing Enabling Innovative Payment Experiences?",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/modern-card-issuing",
        "date": "June 17, 2022",
        "slug": "modern-card-issuing",
        "path": "/blog/modern-card-issuing",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 11,
        "src": "https://simplifipay.com/images/blogs/011.png",
        "alt": "On-Demand Food Delivery Payments",
        "subtitle": "The global market for on-demand food delivery services is projected to reach $259.7 billion by 2027, growing at a global...",
        "title": "Streamlining Payments For The On-Demand Food Delivery Market",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/streamlining-payments-ondemand-delivery",
        "date": "May 06, 2022",
        "slug": "streamlining-payments-ondemand-delivery",
        "path": "/blog/streamlining-payments-ondemand-delivery",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      },
      {
        "id": 12,
        "src": "https://simplifipay.com/images/blogs/012.png",
        "alt": "Gig Payments",
        "subtitle": "According to a study carried out by Visa, 77% of the surveyed gig workers endure times where they need money...",
        "title": "Modern Card Issuance – A Game-changer for Gig Payments",
        "buttonText": "READ MORE",
        "buttonLink": "/blog/modern-card-issuance-for-gig-payments",
        "date": "April 06, 2022",
        "slug": "modern-card-issuance-for-gig-payments",
        "path": "/blog/modern-card-issuance-for-gig-payments",
        "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
      }
    ]},
    "image": "https://cdn.prod.website-files.com/678e5f1a1f6220b154b30471/67922d0f5a3a9c3a856ec2d1_Tinder.svg"
  }
};
