INSERT INTO Users(slack_id, username, first_name) VALUES
('-', '-', 'SimpliFi');

INSERT INTO Locations(location) VALUES
('Dubai, UAE');

INSERT INTO Pages(type, author_id, location_id, path, image, created_on, title, slug) VALUES
('blog', 1, 1, 'components-of-launching-your-own-branded-cards-simplified', '001.png', '2023-09-13 00:00:00',
 'Launching your own card program – SimpliFied', 'Spending across virtually all markets and use cases is increasingly migrating to digital means with cards accounting for the lion''s'),
('blog', 1, 1, 'what-is-global-compliance', '002.jpg', '2023-02-03 00:00:00',
 'Global Compliance SimpliFied', 'Compliance refers to the adherence to a set of regulations and industry standards designed to protect consumers and ensure the'),
('blog', 1, 1, 'what-is-a-virtual-card', '003.jpg', '2022-12-09 00:00:00',
 'What is a Virtual Card | Fintech explained by SimpliFi', 'A Virtual Card is a payment card that exists solely in electronic form. It consists of a unique, randomly- generated'),
('blog', 1, 1, 'what-is-kyc', '004.jpg', '2022-11-11 00:00:00',
 'What is KYC? – Fintech Explained by SimpliFi', 'KYC is one of the most important terms in Fintech, and the financial ecosystem at large.What is KYC, you ask'),
('blog', 1, 1, 'open-loop-payment-system', '005.png', '2022-11-04 00:00:00',
 'What is an Open Loop Payment System? Fintech Explained by SimpliFi', 'Open-loop means any payment method can be used to make payments without having to be part of the system itself'),
('blog', 1, 1, 'launching-card-offerings', '006.jpg', '2022-10-14 00:00:00',
 '9 Things to Consider When Designing a Modern Card Offering', 'In 2022, people and businesses continue to use payment cards every day – if not several times a day'),
('blog', 1, 1, 'modern-card-issuing-vs-legacy-systems', '007.png', '2022-09-02 00:00:00',
 'Modern Card Issuing Vs. Legacy Systems: What is the difference?', 'The magic of seamless, nearly invisible payments is spreading everywhere – on e-commerce sites'),
('blog', 1, 1, 'what-is-payment-tokenization-fintech-explained-by-simplifi', '008.jpg', '2022-08-12 00:00:00',
 'What is Payment Tokenization? – Fintech Explained By SimpliFi', 'Tokenization has become a major buzzword these days and is often mentioned in the same breath as data security, blockchain'),
('blog', 1, 1, 'what-is-a-card-scheme', '009.jpg', '2022-07-08 00:00:00',
 'Card Scheme: Fintech Explained by SimpliFi', 'In any given payment card transaction there are multiple entities involved in the processing of those transactions'),
('blog', 1, 1, 'modern-card-issuing', '010.jpg', '2022-06-17 00:00:00',
 'How is Modern Card Issuing Enabling Innovative Payment Experiences?', 'For decades, legacy payment infrastructure has enabled the payment of goods and services globally, reliably and securely'),
('blog', 1, 1, 'streamlining-payments-ondemand-delivery', '011.png', '2022-05-06 00:00:00',
 'Streamlining Payments For The On-Demand Food Delivery Market', 'The global market for on-demand food delivery services is projected to reach $259.7 billion by 2027, growing at a global'),
('blog', 1, 1, 'modern-card-issuance-for-gig-payments', '012.png', '2022-04-06 00:00:00',
 'Modern Card Issuance – A Game-changer for Gig Payments', 'According to a study carried out by Visa, 77% of the surveyed gig workers endure times where they need money'),
('blog', 1, 1, 'what-is-regtech', '013.jpg', '2022-03-06 00:00:00',
 'What is RegTech? – A Simple Guide', 'RegTech is more than just a buzzword in the global financial and compliance community. So what is RegTech and why'),
('blog', 1, 1, 'what-is-caas', '014.png', '2022-02-25 00:00:00',
 'What is Card as a Service – A Simple Explainer for Businesses', 'In the past, issuing cards to customers was the product of a partnership between a large business and a bank'),
('blog', 1, 1, 'cross-border-payments-challenges', '015.png', '2022-02-16 00:00:00',
 'Cross-border Commerce is a Trillion-Dollar Opportunity – but is your business ready?', 'According to a Juniper study, the value of B2B cross-border payments will exceed $42.7 trillion in 2026, from $34 trillion'),
('blog', 1, 1, 'bnpl-fintech-apis', '016.png', '2022-02-09 00:00:00',
 'BNPL is Exploding! This is Why...', 'With 100 billion in BNPL purchases in 2021, up from 24 billion in 2020 – Buy Now Pay Later (BNPL)'),
('blog', 1, 1, 'virtual-cards-for-company-spending', '017.png', '2022-01-29 00:00:00',
 '5 Reasons to use Virtual Cards for Company Spending in 2022', 'Businesses around the world rely on one of the three following methods to pay their workers and vendors: writing checks'),
('blog', 1, 1, 'building-a-succesful-fintech-solution', '018.png', '2022-01-16 00:00:00',
 'Jot This Down. Quick Notes on Building Your Own Fintech Solution', 'New fintechs are being born every day. But In a space that is getting crowded with dozens of startups entering'),
('blog', 1, 1, 'thinking-about-launching-your-own-fintech-startup-consider-these-3-technical-challenges-first', '019.png', '2021-12-13 00:00:00',
 'Thinking about launching your own FinTech Startup? Consider these 3 technical challenges first', 'The MENA region has seen a surge of fintech startups within the past few years. In November 2020, the region'),
('blog', 1, 1, 'build-or-buy-embedded-finance', '020.png', '2021-11-24 00:00:00',
 'Embedded Finance. Build or Buy?', 'Embedding financial services within your core business offerings promises to unlock new revenue opportunities and reduce operational costs'),
('blog', 1, 1, 'provide-financial-services', '021.png', '2021-11-14 00:00:00',
 'Top 5 reasons why your business needs to start providing financial services now', 'For centuries, financial services have been the banking sector’s birthright. Complex systems, bureaucracy, and compliance restrictions made it'),
('blog', 1, 1, 'embedded-finance-strategy', '022.webp', '2021-11-04 00:00:00',
 'Designing an embedded finance strategy that works for your business', 'In the not-too-distant future, nearly every company will derive a significant portion of its revenue from financial services'),
('blog', 1, 1, 'powering-financial-ownership', '023.png', '2021-10-21 00:00:00',
 'Discover the infrastructure that is powering organizations to reap the benefits of financial ownership', 'Technological advancements are not new to the world of Finance. However, the surge in digital innovation and change in modern-day')
;

INSERT INTO Pages(type, author_id, location_id, path, image, created_on, title, slug) VALUES
('news', 1, 1, 'simplifi-onboards-nqoodlet', '001.jpg', '2024-01-22 00:00:00',
 'SimpliFi® and NQOODLET join forces to transform SME spend management across MENA', 'The Riyadh-based and "Visa Direct Award 2022" winner NQOODLET joins forces with Dubai-based SimpliFi to bring to market a modern'),
('news', 1, 1, 'simplifi-partners-with-lune', '002.jpg', '2023-07-14 00:00:00',
 'SimpliFi® and Hub71 startup Lune partner to drive transformative data enrichment and analytics services to businesses in MENAP', 'SimpliFi, a Cards as a Service (CaaS) platform for MENA and Pakistan, and Lune, a transaction data enrichment and analytics'),
('news', 1, 1, 'simplifi-partners-with-mastercard', '003.png', '2023-06-13 00:00:00',
 'SimpliFi® and Mastercard join forces to enable innovative payment solutions across Middle East, North Africa & Pakistan', 'SimpliFi has partnered with Mastercard to enhance digital payment adoption across the MENAP region. With demand for efficient digital payment'),
('news', 1, 1, 'simplifi-and-alinma-bank-partner-to-expand-digital-payments-solutions-in-ksa', '004.png', '2023-04-06 00:00:00',
 'SimpliFi and Alinma Bank partner to expand digital payments solutions in KSA', 'SimpliFi, the leading Cards as a Service (CaaS) platform in MENA and Pakistan, and Alinma Bank, amongst the most innovative'),
('news', 1, 1, 'simplifi-and-idwise-partner-to-enable-global-standard-ai-driven-identity-verification-and-e-kyc-solutions-in-mena-and-pakistan', '005.png', '2022-10-27 00:00:00',
 'SimpliFi and IDWise® partner to enable global standard AI-driven identity verification and e-KYC solutions in MENA and Pakistan', 'SimpliFi and Gate to Pay, have joined forces to enable businesses to issue scheme-enabled payment cards in Jordan'),
('news', 1, 1, 'adib-egypt-and-simplifi-partner-to-expand-the-digital-payments-ecosystem-in-egypt', '006.jpg', '2022-08-22 00:00:00',
 'ADIB-Egypt and SimpliFi partner to expand the digital payments ecosystem in Egypt', 'This partnership extends SimpliFi’s footprint into 5 markets across MENA & Pakistan.  August 22, 2022– SimpliFi, the leading Cards as'),
('news', 1, 1, 'faysal-bank-and-simplifi-pakistan-partner-to-offer-innovative-digital-financial-services-through-the-fintech-express-program', '007.jpg', '2022-08-16 00:00:00',
 'Faysal Bank & SimpliFi Pakistan partner to offer Innovative Digital Financial Services', 'Fintech Express Program from Faysal Bank is focused on identifying and fostering Fintechs and Startups with promising, high-potential innovative'),
('news', 1, 1, 'simplifi-infinios-partner-to-support-the-growing-fintech-ecosystem-in-mena', '008.jpg', '2022-07-13 00:00:00',
 'SimpliFi & Infinios partner to support the growing Fintech ecosystem in MENA', 'SimpliFi, the leading Cards as a Service (CaaS) platform for MENA and Pakistan, and Infinios Financial Services B.S.C (c) (Infinios)'),
('news', 1, 1, 'simplifi-partners-with-gate-to-pay-to-fast-track-card-issuance-in-jordan', '009.jpg', '2022-06-28 00:00:00',
 'SimpliFi partners with gate to pay to fast-track card issuance in Jordan', 'SimpliFi, the leading Cards as a Service (CaaS) platform for MENA and Pakistan, and Gate to Pay, a regional Fintech'),
('news', 1, 1, 'mdp-and-simplifi-collaborate-to-accelerate-the-expansion-of-payment-solutions-into-the-middle-east-and-african-region', '010.jpg', '2022-05-30 00:00:00',
 'MDP and SimpliFi collaborate to accelerate the expansion of payment solutions into the Middle East and Africa region', 'MDP, the leading payments & card issuing platform signed a partnership with SimpliFi to accelerate expansion into the MIDDLE EAST'),
('news', 1, 1, 'toppan-futurecard-and-fintech-start-up-simplifi-collaborate-to-enable-fast-and-flexible-card-issuance', '011.jpg', '2021-12-29 00:00:00',
 'Toppan FutureCard and Fintech start-up SimpliFi collaborate to enable fast and flexible card Issuance', 'Toppan FutureCard, a Toppan Company, and UAE-based global end-to-end card solutions provider, collaborates with SimpliFi, a Card as a Service'),
('news', 1, 1, 'simplifi-seals-5-1-million-in-funding-to-expand-its-caas-platform-across-menap', '012.jpg', '2021-12-26 00:00:00',
 'SimpliFi seals $5.1 million in funding to expand its CaaS platform across MENAP', 'New investors, Global Founders Capital and 4DX Ventures, are joined by existing investors, Raed Ventures and Rally Cap Ventures   UAE'),
('news', 1, 1, 'veriff-partners-with-simplifi-to-provide-trusted-and-secure-identity-verification-for-instant-card-issuance', '013.jpg', '2021-09-28 00:00:00',
 'Veriff Partners with SimpliFi to Provide Trusted and Secure Identity Verification for Instant Card Issuance', 'Identity verification technology enables SimpliFi customers to seamlessly issue virtual or physical payment cards in MENA and Pakistan Veriff, a'),
('news', 1, 1, 'simplifi-emerges-from-stealth-mode-to-democratize-card-issuance-in-menap', '014.jpg', '2021-08-02 00:00:00',
 'SimpliFi emerges from stealth mode to democratize card issuance in MENAP', 'Backing from Raed Ventures along with a number of regional and global investors puts SimpliFi in a strong position for.')
;
